/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package tesis.ages.Ventanas;

import Controladores.CompraController;
import com.toedter.calendar.JDateChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jolma
 */
public class frmCompra extends javax.swing.JDialog {

    public static frmProducto fp;
    public static frmCompra fc;
    public static frmVenta fv;
    public static frmReporte fr;
    public static frmNotificaciones fn;
    private JTable tablaProductos;
    private CompraController compraController;
    private DefaultTableModel modeloTabla;
    private JDateChooser jDateFecha;
    
    public frmCompra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        // Inicializar el controlador
        compraController = new CompraController();
        
        // Inicializar el JDateChooser con la fecha actual
        jDateFecha = new JDateChooser();
        jDateFecha.setDateFormatString("dd/MM/yyyy");
        jDateFecha.setDate(new java.util.Date());
        jDateFecha.setEnabled(false); // Deshabilitar la edición de la fecha
        
        // Agregar el JDateChooser al panel
        jPanel2.add(jDateFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 200, 30));
        
        // Inicializar la tabla
        inicializarTabla();
    }

    private void inicializarTabla() {
        modeloTabla = new DefaultTableModel(compraController.getDatosTabla(), compraController.getNombresColumnas()) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tablaProductos = new JTable(modeloTabla);
        jScrollPane1.setViewportView(tablaProductos);
    }
    
    private void actualizarTabla() {
        modeloTabla.setDataVector(compraController.getDatosTabla(), compraController.getNombresColumnas());
    }

    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jBtoCompra = new javax.swing.JButton();
        jBtoVenta = new javax.swing.JButton();
        jBtoReporte = new javax.swing.JButton();
        jBtoNotificaciones = new javax.swing.JButton();
        jBtoProducto = new javax.swing.JButton();
        jTextFactura = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFactura1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFactura2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFactura3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jBtoConfirmar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jBtoConfirmar1 = new javax.swing.JButton();
        jBtoConfirmar2 = new javax.swing.JButton();
        jBtoConfirmar3 = new javax.swing.JButton();
        jTextFactura4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ICompra");

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(525, 230));

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jBtoCompra.setBackground(new java.awt.Color(0, 153, 204));
        jBtoCompra.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jBtoCompra.setText("Compra");
        jBtoCompra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBtoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtoCompraActionPerformed(evt);
            }
        });

        jBtoVenta.setBackground(new java.awt.Color(0, 153, 204));
        jBtoVenta.setText("Venta");
        jBtoVenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBtoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtoVentaActionPerformed(evt);
            }
        });

        jBtoReporte.setBackground(new java.awt.Color(0, 153, 204));
        jBtoReporte.setText("Reportes");
        jBtoReporte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBtoReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtoReporteActionPerformed(evt);
            }
        });

        jBtoNotificaciones.setBackground(new java.awt.Color(0, 153, 204));
        jBtoNotificaciones.setText("Notificaciones");
        jBtoNotificaciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBtoNotificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtoNotificacionesActionPerformed(evt);
            }
        });

        jBtoProducto.setBackground(new java.awt.Color(0, 153, 204));
        jBtoProducto.setText("Producto");
        jBtoProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBtoProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtoProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jBtoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jBtoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jBtoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jBtoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jBtoNotificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jBtoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jBtoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jBtoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jBtoNotificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jBtoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTextFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFacturaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("N° Factura");

        jTextFactura1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFactura1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Referencia");

        jTextFactura2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFactura2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Cantidad");

        jTextFactura3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFactura3ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Valor U.");

        jBtoConfirmar.setBackground(new java.awt.Color(0, 153, 204));
        jBtoConfirmar.setText("Eliminar Producto");
        jBtoConfirmar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBtoConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtoConfirmarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTextPane1);

        jBtoConfirmar1.setBackground(new java.awt.Color(0, 153, 204));
        jBtoConfirmar1.setText("Agregar Producto");
        jBtoConfirmar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBtoConfirmar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtoConfirmar1ActionPerformed(evt);
            }
        });

        jBtoConfirmar2.setBackground(new java.awt.Color(0, 153, 204));
        jBtoConfirmar2.setText("Cancelar compra");
        jBtoConfirmar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBtoConfirmar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtoConfirmar2ActionPerformed(evt);
            }
        });

        jBtoConfirmar3.setBackground(new java.awt.Color(0, 153, 204));
        jBtoConfirmar3.setText("Registrar compra");
        jBtoConfirmar3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBtoConfirmar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtoConfirmar3ActionPerformed(evt);
            }
        });

        jTextFactura4.setText("asd");
        jTextFactura4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFactura4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFactura3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jTextFactura2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFactura1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 892, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFactura4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(299, 299, 299)
                        .addComponent(jBtoConfirmar1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jBtoConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jBtoConfirmar2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jBtoConfirmar3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addGap(12, 12, 12)
                        .addComponent(jTextFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addGap(12, 12, 12)
                        .addComponent(jTextFactura1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addGap(12, 12, 12)
                        .addComponent(jTextFactura2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(12, 12, 12)
                        .addComponent(jTextFactura3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtoConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtoConfirmar2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBtoConfirmar1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtoConfirmar3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jTextFactura4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 1150, 450));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setText("A.G.E.S.");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 140, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1186, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtoCompraActionPerformed
        dispose();
        fc=new frmCompra(null,true);
        fc.setVisible(true);
    }//GEN-LAST:event_jBtoCompraActionPerformed

    private void jBtoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtoVentaActionPerformed
        dispose();
        fv=new frmVenta(null,true);
        fv.setVisible(true);
    }//GEN-LAST:event_jBtoVentaActionPerformed

    private void jBtoReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtoReporteActionPerformed
        dispose();
        fr=new frmReporte(null,true);
        fr.setVisible(true);
    }//GEN-LAST:event_jBtoReporteActionPerformed

    private void jBtoNotificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtoNotificacionesActionPerformed
        dispose();
        fn=new frmNotificaciones(null,true);
        fn.setVisible(true);
    }//GEN-LAST:event_jBtoNotificacionesActionPerformed

    private void jBtoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtoProductoActionPerformed
        dispose();
        fp=new frmProducto(null,true);
        fp.setVisible(true);
    }//GEN-LAST:event_jBtoProductoActionPerformed

    private void jTextFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFacturaActionPerformed

    private void jTextFactura1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFactura1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFactura1ActionPerformed

    private void jTextFactura2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFactura2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFactura2ActionPerformed

    private void jTextFactura3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFactura3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFactura3ActionPerformed

    private void jBtoConfirmarActionPerformed(java.awt.event.ActionEvent evt) {
        String idStr = JOptionPane.showInputDialog("Ingrese el ID del producto a eliminar:");
        if (idStr != null && !idStr.isEmpty()) {
            try {
                int id = Integer.parseInt(idStr);
                compraController.eliminarProducto(id);
                actualizarTabla();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "El ID debe ser un número");
            }
        }
    }

    private void jBtoConfirmar1ActionPerformed(java.awt.event.ActionEvent evt) {
        String numeroFactura = jTextFactura.getText().trim();
        String referencia = jTextFactura1.getText().trim();
        String cantidadStr = jTextFactura2.getText().trim();
        String valorUnitarioStr = jTextFactura3.getText().trim();
        
        // Validar campos vacíos
        if (numeroFactura.isEmpty() || referencia.isEmpty() || cantidadStr.isEmpty() || valorUnitarioStr.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios");
            return;
        }
        
        // Validar número de factura
        if (!compraController.validarNumeroFactura(numeroFactura)) {
            JOptionPane.showMessageDialog(null, "El número de factura debe ser un número positivo");
            return;
        }
        
        try {
            int cantidad = Integer.parseInt(cantidadStr);
            int valorUnitario = Integer.parseInt(valorUnitarioStr);
            
            if (cantidad <= 0 || valorUnitario <= 0) {
                JOptionPane.showMessageDialog(null, "La cantidad y el valor unitario deben ser números positivos");
                return;
            }
            
            // Obtener la fecha actual
            java.util.Date fechaActual = new java.util.Date();
            
            // Formatear fecha
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
            String fecha = sdf.format(fechaActual);
            
            // Agregar producto a la tabla
            compraController.agregarProductoATabla(numeroFactura, fecha, referencia, cantidad, valorUnitario);
            actualizarTabla();
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "La cantidad y el valor unitario deben ser números");
        }
    }

    private void jBtoConfirmar2ActionPerformed(java.awt.event.ActionEvent evt) {
        compraController.limpiarTabla();
        actualizarTabla();
        jTextFactura.setText("");
        jTextFactura1.setText("");
        jTextFactura2.setText("");
        jTextFactura3.setText("");
    }

    private void jBtoConfirmar3ActionPerformed(java.awt.event.ActionEvent evt) {
        if (compraController.registrarCompra()) {
            actualizarTabla();
            jTextFactura.setText("");
            jTextFactura1.setText("");
            jTextFactura2.setText("");
            jTextFactura3.setText("");
        }
    }

    private void jTextFactura4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFactura4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFactura4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmCompra dialog = new frmCompra(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtoCompra;
    private javax.swing.JButton jBtoConfirmar;
    private javax.swing.JButton jBtoConfirmar1;
    private javax.swing.JButton jBtoConfirmar2;
    private javax.swing.JButton jBtoConfirmar3;
    private javax.swing.JButton jBtoNotificaciones;
    private javax.swing.JButton jBtoProducto;
    private javax.swing.JButton jBtoReporte;
    private javax.swing.JButton jBtoVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFactura;
    private javax.swing.JTextField jTextFactura1;
    private javax.swing.JTextField jTextFactura2;
    private javax.swing.JTextField jTextFactura3;
    private javax.swing.JTextField jTextFactura4;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
