/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package tesis.ages.Ventanas;

import Controladores.ProductoController;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jolma
 */
public class frmProducto extends javax.swing.JDialog {

    public static frmProducto fp;
    public static frmCompra fc;
    public static frmVenta fv;
    public static frmReporte fr;
    public static frmNotificaciones fn;
    public static frmProductoEliminar fps;
    public static frmProductoEditar fpe;
    public static frmProductoNuevo fpn;
    private JTable tablaProductos;
    private JScrollPane scrollPane;
    private DefaultTableModel model;

    public frmProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        // Inicializar la instancia estática
        fp = this;
        
        // Crear y configurar la tabla
        actualizarTabla();
    }
    
    public void actualizarTabla() {
        ProductoController productoController = new ProductoController();
        Object[][] datos = productoController.getDatosProductos();
        String[] columnas = productoController.getNombresColumnas();
        
        model = new DefaultTableModel(datos, columnas) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        if (tablaProductos == null) {
            tablaProductos = new JTable(model);
            tablaProductos.setFillsViewportHeight(true);
            
            // Configurar el scroll pane
            scrollPane = new JScrollPane(tablaProductos);
            scrollPane.setBounds(150, 50, 400, 200);
            
            // Reemplazar el JTextArea con la tabla
            jPanel2.remove(jScrollPane2);
            jPanel2.add(scrollPane);
        } else {
            tablaProductos.setModel(model);
            tablaProductos.revalidate();
            tablaProductos.repaint();
        }
    }

    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jBtoCompra = new javax.swing.JButton();
        jBtoVenta = new javax.swing.JButton();
        jBtoReporte = new javax.swing.JButton();
        jBtoNotificaciones = new javax.swing.JButton();
        jBtoProducto = new javax.swing.JButton();
        jBtoNuevo = new javax.swing.JButton();
        jBtoEditar = new javax.swing.JButton();
        jBtoEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("IProducto");

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jBtoProducto.setPreferredSize(new java.awt.Dimension(115, 33));
        jBtoCompra.setPreferredSize(new java.awt.Dimension(115, 33));
        jBtoVenta.setPreferredSize(new java.awt.Dimension(115, 33));
        jBtoReporte.setPreferredSize(new java.awt.Dimension(115, 33));
        jBtoNotificaciones.setPreferredSize(new java.awt.Dimension(115, 33));

        jBtoCompra.setBackground(new java.awt.Color(0, 153, 204));
        jBtoCompra.setText("Compra");
        jBtoCompra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBtoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtoCompraActionPerformed(evt);
            }
        });

        jBtoVenta.setBackground(new java.awt.Color(0, 153, 204));
        jBtoVenta.setText("Venta");
        jBtoVenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBtoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtoVentaActionPerformed(evt);
            }
        });

        jBtoReporte.setBackground(new java.awt.Color(0, 153, 204));
        jBtoReporte.setText("Reportes");
        jBtoReporte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBtoReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtoReporteActionPerformed(evt);
            }
        });

        jBtoNotificaciones.setBackground(new java.awt.Color(0, 153, 204));
        jBtoNotificaciones.setText("Notificaciones");
        jBtoNotificaciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBtoNotificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtoNotificacionesActionPerformed(evt);
            }
        });

        jBtoProducto.setBackground(new java.awt.Color(0, 153, 204));
        jBtoProducto.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jBtoProducto.setText("Producto");
        jBtoProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBtoProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtoProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jBtoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jBtoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jBtoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jBtoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jBtoNotificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jBtoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jBtoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jBtoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jBtoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jBtoNotificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jBtoNuevo.setBackground(new java.awt.Color(0, 153, 204));
        jBtoNuevo.setText("Nuevo");
        jBtoNuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBtoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtoNuevoActionPerformed(evt);
            }
        });

        jBtoEditar.setBackground(new java.awt.Color(0, 153, 204));
        jBtoEditar.setText("Editar");
        jBtoEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBtoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtoEditarActionPerformed(evt);
            }
        });

        jBtoEliminar.setBackground(new java.awt.Color(0, 153, 204));
        jBtoEliminar.setText("Eliminar");
        jBtoEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBtoEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtoEliminarActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jBtoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jBtoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 580, 270));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36));
        jLabel1.setText("A.G.E.S.");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 140, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, Short.MAX_VALUE)
        );

        // Ajustar el tamaño del área de la tabla
        jScrollPane2.setPreferredSize(new java.awt.Dimension(500, 250));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtoEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtoEliminarActionPerformed
        fps=new frmProductoEliminar(null,true);
        fps.setVisible(true);
    }//GEN-LAST:event_jBtoEliminarActionPerformed

    private void jBtoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtoEditarActionPerformed
        fpe=new frmProductoEditar(null,true);
        fpe.setVisible(true);
    }//GEN-LAST:event_jBtoEditarActionPerformed

    private void jBtoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtoNuevoActionPerformed
        fpn=new frmProductoNuevo(null,true);
        fpn.setVisible(true);
    }//GEN-LAST:event_jBtoNuevoActionPerformed

    private void jBtoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtoProductoActionPerformed
        dispose();
        fp=new frmProducto(null,true);
        fp.setVisible(true);
    }//GEN-LAST:event_jBtoProductoActionPerformed

    private void jBtoNotificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtoNotificacionesActionPerformed
        dispose();
        fn=new frmNotificaciones(null,true);
        fn.setVisible(true);
    }//GEN-LAST:event_jBtoNotificacionesActionPerformed

    private void jBtoReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtoReporteActionPerformed
        dispose();
        fr=new frmReporte(null,true);
        fr.setVisible(true);
    }//GEN-LAST:event_jBtoReporteActionPerformed

    private void jBtoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtoVentaActionPerformed
        dispose();
        fv=new frmVenta(null,true);
        fv.setVisible(true);
    }//GEN-LAST:event_jBtoVentaActionPerformed

    private void jBtoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtoCompraActionPerformed
        dispose();
        fc=new frmCompra(null,true);
        fc.setVisible(true);
    }//GEN-LAST:event_jBtoCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmProducto dialog = new frmProducto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtoCompra;
    private javax.swing.JButton jBtoEditar;
    private javax.swing.JButton jBtoEliminar;
    private javax.swing.JButton jBtoNotificaciones;
    private javax.swing.JButton jBtoNuevo;
    private javax.swing.JButton jBtoProducto;
    private javax.swing.JButton jBtoReporte;
    private javax.swing.JButton jBtoVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}

