package tesis.ages.Ventanas;

import com.toedter.calendar.JDateChooser;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.io.IOException;
import java.text.SimpleDateFormat;
import Controladores.ReportesController;

/**
 *
 * @author jolma
 */
public class frmReporte extends javax.swing.JDialog {

    public static frmProducto fp;
    public static frmCompra fc;
    public static frmVenta fv;
    public static frmReporte fr;
    public static frmNotificaciones fn;
    private JDateChooser jDateFechaInicio;
    private JDateChooser jDateFechaFin;

    public frmReporte(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        // Inicializar los campos de fecha antes del diseño
        jDateFechaInicio = new JDateChooser();
        jDateFechaInicio.setDateFormatString("dd/MM/yyyy");
        
        jDateFechaFin = new JDateChooser();
        jDateFechaFin.setDateFormatString("dd/MM/yyyy");
        
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jBtoCompra = new javax.swing.JButton();
        jBtoVenta = new javax.swing.JButton();
        jBtoReporte = new javax.swing.JButton();
        jBtoNotificaciones = new javax.swing.JButton();
        jBtoProducto = new javax.swing.JButton();
        jCheckBoxProductos = new javax.swing.JCheckBox();
        jTextFechaInicio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFechaFin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jCheckBoxCompras = new javax.swing.JCheckBox();
        jCheckBoxVentas = new javax.swing.JCheckBox();
        jBtoConfirmar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("IReporte");

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(528, 230));

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jBtoCompra.setBackground(new java.awt.Color(0, 153, 204));
        jBtoCompra.setText("Compra");
        jBtoCompra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBtoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtoCompraActionPerformed(evt);
            }
        });

        jBtoVenta.setBackground(new java.awt.Color(0, 153, 204));
        jBtoVenta.setText("Venta");
        jBtoVenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBtoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtoVentaActionPerformed(evt);
            }
        });

        jBtoReporte.setBackground(new java.awt.Color(0, 153, 204));
        jBtoReporte.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jBtoReporte.setText("Reportes");
        jBtoReporte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBtoReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtoReporteActionPerformed(evt);
            }
        });

        jBtoNotificaciones.setBackground(new java.awt.Color(0, 153, 204));
        jBtoNotificaciones.setText("Notificaciones");
        jBtoNotificaciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBtoNotificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtoNotificacionesActionPerformed(evt);
            }
        });

        jBtoProducto.setBackground(new java.awt.Color(0, 153, 204));
        jBtoProducto.setText("Producto");
        jBtoProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBtoProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtoProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jBtoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jBtoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jBtoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jBtoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jBtoNotificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jBtoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jBtoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jBtoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jBtoNotificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jBtoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jCheckBoxProductos.setText("Productos en Stock");
        jCheckBoxProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxProductosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Fecha Inicio");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Fecha Fin");

        jCheckBoxCompras.setText("Compras");
        jCheckBoxCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxComprasActionPerformed(evt);
            }
        });

        jCheckBoxVentas.setText("Ventas");
        jCheckBoxVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxVentasActionPerformed(evt);
            }
        });

        jBtoConfirmar.setBackground(new java.awt.Color(0, 153, 204));
        jBtoConfirmar.setText("Confirmar");
        jBtoConfirmar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBtoConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtoConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxCompras)
                            .addComponent(jCheckBoxProductos))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCheckBoxVentas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtoConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(28, 28, 28)
                        .addComponent(jDateFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28)
                        .addComponent(jDateFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jDateFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jDateFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jCheckBoxCompras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxVentas)
                    .addComponent(jBtoConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxProductos)
                .addGap(28, 28, 28))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 280));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setText("A.G.E.S.");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 140, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtoProductoActionPerformed
        dispose();
        fp=new frmProducto(null,true);
        fp.setVisible(true);
    }//GEN-LAST:event_jBtoProductoActionPerformed

    private void jBtoNotificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtoNotificacionesActionPerformed
        dispose();
        fn=new frmNotificaciones(null,true);
        fn.setVisible(true);
    }//GEN-LAST:event_jBtoNotificacionesActionPerformed

    private void jBtoReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtoReporteActionPerformed
        dispose();
        fr=new frmReporte(null,true);
        fr.setVisible(true);
    }//GEN-LAST:event_jBtoReporteActionPerformed

    private void jBtoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtoVentaActionPerformed
        dispose();
        fv=new frmVenta(null,true);
        fv.setVisible(true);
    }//GEN-LAST:event_jBtoVentaActionPerformed

    private void jBtoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtoCompraActionPerformed
        dispose();
        fc=new frmCompra(null,true);
        fc.setVisible(true);
    }//GEN-LAST:event_jBtoCompraActionPerformed

    private void jCheckBoxProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxProductosActionPerformed

    private void jCheckBoxComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxComprasActionPerformed

    private void jCheckBoxVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxVentasActionPerformed

    private void jBtoConfirmarActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            // Validar fechas
            Date fechaInicio = jDateFechaInicio.getDate();
            Date fechaFin = jDateFechaFin.getDate();
            
            if (fechaInicio == null || fechaFin == null) {
                JOptionPane.showMessageDialog(this, "Por favor seleccione ambas fechas", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (fechaFin.before(fechaInicio)) {
                JOptionPane.showMessageDialog(this, "La fecha final debe ser mayor a la fecha inicial", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Validar que al menos un checkbox esté seleccionado
            if (!jCheckBoxCompras.isSelected() && !jCheckBoxVentas.isSelected() && !jCheckBoxProductos.isSelected()) {
                JOptionPane.showMessageDialog(this, "Por favor seleccione al menos un tipo de reporte", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            ReportesController controller = new ReportesController();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyyMMdd");
            String fechaInicioStr = dateFormat.format(fechaInicio);
            String fechaFinStr = dateFormat.format(fechaFin);
            
            // Generar reportes según los checkboxes seleccionados
            if (jCheckBoxCompras.isSelected()) {
                String rutaArchivo = "Reporte_Compras_" + fechaInicioStr + "_" + fechaFinStr + ".csv";
                controller.generarReporteCompras(fechaInicio, fechaFin, rutaArchivo);
                JOptionPane.showMessageDialog(this, "Reporte de compras generado: " + rutaArchivo);
            }
            
            if (jCheckBoxVentas.isSelected()) {
                String rutaArchivo = "Reporte_Ventas_" + fechaInicioStr + "_" + fechaFinStr + ".csv";
                controller.generarReporteVentas(fechaInicio, fechaFin, rutaArchivo);
                JOptionPane.showMessageDialog(this, "Reporte de ventas generado: " + rutaArchivo);
            }
            
            if (jCheckBoxProductos.isSelected()) {
                String rutaArchivo = "Reporte_Productos.csv";
                controller.generarReporteProductos(rutaArchivo);
                JOptionPane.showMessageDialog(this, "Reporte de productos generado: " + rutaArchivo);
            }
            
        } catch (SQLException | IOException e) {
            JOptionPane.showMessageDialog(this, "Error al generar el reporte: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Método para obtener la fecha de inicio
    public Date getFechaInicio() {
        return jDateFechaInicio.getDate();
    }

    // Método para obtener la fecha de fin
    public Date getFechaFin() {
        return jDateFechaFin.getDate();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmReporte dialog = new frmReporte(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtoCompra;
    private javax.swing.JButton jBtoConfirmar;
    private javax.swing.JButton jBtoNotificaciones;
    private javax.swing.JButton jBtoProducto;
    private javax.swing.JButton jBtoReporte;
    private javax.swing.JButton jBtoVenta;
    private javax.swing.JCheckBox jCheckBoxCompras;
    private javax.swing.JCheckBox jCheckBoxProductos;
    private javax.swing.JCheckBox jCheckBoxVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFechaFin;
    private javax.swing.JTextField jTextFechaInicio;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
